### ISSUE TITLE
Cannot view enrollments

### ISSUE THREAD

**Issue by jreedy-riis** [energywebfoundation/switchboard-dapp#760]
### Description
Hello, when logging into Switchboard, I am unable to view any enrollments I have for both myself and for my assets. The console is throwing a bunch of undefined errors.

### Images

<img width="1728" alt="Screen Shot 2022-09-06 at 10 20 47 AM" src="https://user-images.githubusercontent.com/87768696/188660442-7ca6bf8c-b7df-4e59-856d-85450e789d78.png">
<img width="1728" alt="Screen Shot 2022-09-06 at 10 20 41 AM" src="https://user-images.githubusercontent.com/87768696/188660451-d2b61978-3d3c-4af8-9557-458ed23ddff6.png">
<img width="1728" alt="Screen Shot 2022-09-06 at 10 20 35 AM" src="https://user-images.githubusercontent.com/87768696/188660458-a53b220d-4c29-4d92-89a2-0a85dbf18df5.png">

**Comment by jrhender** [comment]
@jreedy-riis thank you for reporting. Was this previously working for this DID?

If you logout and login again, does the issue persist?

**Comment by jreedy-riis** [comment]
Hi, yes this DID worked previously. Logging out and then back in does not fix the issue. All of the DIDs I have been using show this error (even my newest ones that have only interacted with iam-client-lib 6.x.x). I did just notice for two DIDs I have that are org owners, I can see their previous enrollments (which were claims where the owner DID requested a role and then the same owner DID approved it right after). However, the enrollment requests for the owner DIDs do not show up either.

**Comment by jrhender** [comment]
Thanks for the additional information. Are you using the https://switchboard-dev.energyweb.org/ environment?

**Comment by jreedy-riis** [comment]
Yes I am

**Comment by jrhender** [comment]
Thanks for confirming. Your screenshots show the "Revocable Enrolments" tab. What do the "Enrolment Requests" and "My Enrolment" tabs look like? From your description of the issue, it sounds like it is an empty list (expect for the org owners), but you expect it to be populated with enrolment requests.

**Comment by jreedy-riis** [comment]
Oh sorry about that, I meant to have the enrollment requests shown. However, it seems that enrollment requests and enrollments are not showing up (for assets as well). Therefore I cannot approve someone into a role, nor publish a VC to my DID document. The enrollments tab for non-admin should show a few roles that have already been approved. While the admin account should show existing requests that have been approved, revoked, or pending.

### Non-admin
<img width="1728" alt="Screen Shot 2022-09-06 at 11 26 51 AM" src="https://user-images.githubusercontent.com/87768696/188674973-eb39b7d9-e9ae-4afc-8f4d-83215672fb3b.png">
<img width="1728" alt="Screen Shot 2022-09-06 at 11 24 18 AM" src="https://user-images.githubusercontent.com/87768696/188675001-1d3b197d-2479-4a93-9305-c97f6ae91687.png">

### Admin / Owner
<img width="1728" alt="Screen Shot 2022-09-06 at 11 27 22 AM" src="https://user-images.githubusercontent.com/87768696/188675024-729d9921-3913-4991-ac0d-21c91a775b10.png">

<img width="1728" alt="Screen Shot 2022-09-06 at 11 28 08 AM" src="https://user-images.githubusercontent.com/87768696/188675120-535e7340-a7cf-4d05-b0c6-278193ffbedb.png">

**Comment by jrhender** [comment]
@jreedy-riis Just now, we deployed a new version of Switchboard to the `dev` environment (which has a fix for https://github.com/energywebfoundation/switchboard-dapp/issues/744 by the way). Could you do a refresh of your browser to get the latest version of Switchboard (you may need to do a refresh that clears the browser cache, for example using ctrl-F5 in Chrome on Windows) and confirm whether or not the issue persists please?

**Comment by jreedy-riis** [comment]
Awesome to hear about the #744 fix, however, I am still getting the error after clearing the cache on both Firefox and Chrome. I did just create a brand new MetaMask account and enroll into a role. Now for only that DID I can see my enrollment requests. But on the admin approver DID, I cannot see the request to approve it.

**Comment by jrhender** [comment]
Ah, I think I might know what the issue is. We're making some changes to how the authority of credential issuers is verified. Plausibly that is the root cause here. Two things to check for your case:
1. Are the enrolment requests that you're expecting to see for roles whose allowed issuer is another role?
2. If the answer to the above is yes, does your issuer DID have the role credential "published"?

Also, I'm being told by the team that #744 is only partially fixed. Publishing is possible for assets now but the "My Enrolments" list doesn't reflect this correctly yet.

**Comment by jreedy-riis** [comment]
Ah, yes the issuer of my roles is another role. If the role credential "published" would be visible on its DID document, then no I do not see it.

**Comment by jrhender** [comment]
> If the role credential "published" would be visible on its DID document, then no I do not see it.

Yes, after publishing, it should be visible on its DID document.

Did the DID for whom you expect to see a role request under "Enrolment Requests" obtain the "issuer" role? Is issuer role one of the `admin` roles from your screenshot?

**Comment by jreedy-riis** [comment]
Oh I see, I misunderstood. Yes the role credential was published before hand and yes I do see the role on the DID document. Also, my mistake this example role request we are talking about (that I just enrolled into with the a new account) has a DID issuer. However, before I made that new account, I was testing with roles that had other roles as issuers. So it does not seem to be working with DID issuers or role issuers.

### Issuer DID
<img width="1726" alt="Screen Shot 2022-09-06 at 3 40 53 PM" src="https://user-images.githubusercontent.com/87768696/188724181-bef2f3d6-3585-421b-b7ea-1b48e2ce5a9b.png">

### Role with DID Issuer
<img width="1726" alt="Screen Shot 2022-09-06 at 3 37 40 PM" src="https://user-images.githubusercontent.com/87768696/188724317-3b655911-f48d-4651-8475-06ede34c1d80.png">

### User Request
<img width="1728" alt="Screen Shot 2022-09-06 at 3 33 24 PM" src="https://user-images.githubusercontent.com/87768696/188723262-ce356410-b4ae-4d14-a85a-b0d8b9a4ce60.png">

### Issuer Enrollment Requests
<img width="1726" alt="Screen Shot 2022-09-06 at 3 44 15 PM" src="https://user-images.githubusercontent.com/87768696/188724915-9033a9a5-b668-4007-a8f4-0d96a20b8e18.png">

**Comment by jrhender** [comment]
Thanks for the additional screenshots @jreedy-riis . We've released an additional filter into the enrolments list on Switchboard. Could you check if this has changed the behaviour on your end please?

**Comment by jreedy-riis** [comment]
Yes it is working now, thank you!
